export const dummyData = [
  {
    id: "001",
    title: "Duplex",
    loc: "Abuja,Nigeria",
    price: 2000,
    bedroom: 5,
    bathroom: 2,
    imgUrl: ["/img14.jpg", "/img12.jpg", "/img13.jpg"],
  },
  {
    id: "002",
    title: "Bungalow",
    loc: "Lagos,Nigeria",
    price: 1500,
    bedroom: 3,
    bathroom: 2,
    imgUrl: ["/img2.jpg", "/img5.jpg", "/img6.jpg"],
  },
  {
    id: "003",
    title: "Flat",
    loc: "Enugu,Nigeria",
    price: 500,
    bedroom: 2,
    bathroom: 1,
    imgUrl: ["/img3.jpg", "/img5.jpg", "/img1.jpg"],
  },
  {
    id: "004",
    title: "Duplex",
    loc: "Porto Novo,Benin",
    price: 6000,
    bedroom: 5,
    bathroom: 2,
    imgUrl: ["/img4.jpg", "/img6.jpg", "/img2.jpg"],
  },
  {
    id: "005",
    title: "Estate",
    loc: "Abuja,Nigeria",
    price: 100000,
    bedroom: 45,
    bathroom: 10,
    imgUrl: ["/img5.jpg", "/img6.jpg", "/img1.jpg"],
  },
  {
    id: "006",
    title: "Duplex",
    loc: "Lagos,Nigeria",
    price: 4000,
    bedroom: 9,
    bathroom: 2,
    imgUrl: ["/img6.jpg", "/img7.jpg", "/img2.jpg"],
  },
  {
    id: "007",
    title: "Flat",
    loc: "Anambra,Nigeria",
    price: 1000,
    bedroom: 5,
    bathroom: 2,
    imgUrl: ["/img7.jpg", "/img10.jpg", "/img13.jpg"],
  },
  {
    id: "008",
    title: "Bungalow",
    loc: "Delta,Nigeria",
    price: 1000,
    bedroom: 5,
    bathroom: 2,
    imgUrl: ["/img8.jpg", "/img5.jpg", "/img2.jpg"],
  },
  {
    id: "009",
    title: "Duplex",
    loc: "Ebonyi,Nigeria",
    price: 6000,
    bedroom: 10,
    bathroom: 4,
    imgUrl: ["/img9.jpg", "/img7.jpg", "/img8.jpg"],
  },
  {
    id: "010",
    title: "Duplex",
    loc: "Abuja,Nigeria",
    price: 2000,
    bedroom: 4,
    bathroom: 2,
    imgUrl: ["/img10.jpg", "/img1.jpg", "/img12.jpg"],
  },
];
